### ISSUE TITLE
请问一下

### ISSUE THREAD

**Issue by ylmyg** [jacky4631/sfb#1]
请问我下载下来运行，是不是也运行不了，因为没有后端？

**Comment by jacky4631** [comment]
设置了默认演示地址，可以运行

**Comment by ylmyg** [comment]
请问一下 出现这种情况怎么办呢？
![1714439306260](https://github.com/jacky4631/sfb/assets/7122217/1cdda5df-57a3-4b71-b304-3796adca1cb6)
@jacky4631

**Comment by jacky4631** [comment]
请使用flutter 3.7.10   dart 2.19.6

**Comment by yangdada0408** [comment]
请问一下编译没有问题，app运行的时候闪退报ClassNotFoundException: com.ut.device.UTDevice是什么原因
java sdk版本是 jdk-11.0.16.jdk 
flutter sdk Flutter version 3.10.0 Dart version 3.0.0
编译环境是macos arm环境
下面是app运行时闪退时系统捕获的报错：
安卓的阿里百川安全图片已配置
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/ut/device/UTDevice;
 at com.alibaba.baichuan.trade.common.AlibcTradeCommon.init(Unknown Source:16)
 at com.alibaba.baichuan.trade.biz.AlibcTradeBiz.init(Unknown Source:15)
 at com.alibaba.baichuan.android.trade.AlibcTradeSDK.b(Unknown Source:3)
 at com.alibaba.baichuan.android.trade.AlibcTradeSDK.a(Unknown Source:0)
 at com.alibaba.baichuan.android.trade.AlibcTradeSDK$1.run(Unknown Source:4)
 at android.os.Handler.handleCallback(Handler.java:958)
 at android.os.Handler.dispatchMessage(Handler.java:99)
 at android.os.Looper.loopOnce(Looper.java:224)
 at android.os.Looper.loop(Looper.java:318)
 at android.os.HandlerThread.run(HandlerThread.java:67)
Caused by: java.lang.ClassNotFoundException: com.ut.device.UTDevice
 ... 10 more
